# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_number',
            field=models.IntegerField(default=0),
        ),
    ]
