# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_join_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
