# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170102_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
    ]
