# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170107_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
