# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170107_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='group',
        ),
    ]
