# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170107_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionHeart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_heart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CommentShip',
            new_name='CommentHeart',
        ),
        migrations.RemoveField(
            model_name='discussionship',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussionship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='discussionship',
            name='member',
        ),
        migrations.AddField(
            model_name='comment',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Membership'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DiscussionShip',
        ),
        migrations.AddField(
            model_name='discussionheart',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Discussion'),
        ),
        migrations.AddField(
            model_name='discussionheart',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AddField(
            model_name='discussionheart',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Membership'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Discussion'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Membership'),
        ),
    ]
