# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170108_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Membership'),
            preserve_default=False,
        ),
    ]
