# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_event_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventship',
            old_name='is_leader',
            new_name='is_join',
        ),
    ]
