# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170108_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_day',
            new_name='deadline_date',
        ),
    ]
