# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170108_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='classification',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Classification'),
        ),
    ]
