# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_membership_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Classification'),
        ),
    ]
