# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170110_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_pic',
            field=models.ImageField(default='/static/media/group/default.png', upload_to='/static/media/group/'),
        ),
    ]
