# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170110_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_pic',
            field=models.ImageField(default='/static/media/user/default.png', upload_to='static/media/user/'),
        ),
    ]
