# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170110_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='name',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, to='api.Classification'),
        ),
    ]
